name: Rebuild README
on:
  repository_dispatch:
    types: [rebuild-readme-command]

jobs:
  rebuild_readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      # Rebuild README
      - name: Rebuild README
        shell: bash
        run: |
          make init
          make readme/deps
          make readme

      # Commit changes (if any) to the PR branch
      - uses: cloudposse/actions/github/git-push@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          GITHUB_HEAD_REF: ${{ github.event.client_payload.pull_request.head.ref }}
          GIT_COMMIT_MESSAGE: "Updated README.md"

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.9.0
        with:
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
