# https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/getting-started.md
# https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/examples.md
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows

name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Slash Command Dispatch
        uses: cloudposse/actions/github/slash-command-dispatch@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: aknysh/t3
          commands: rebuild-readme, terraform-fmt, assign-labels, assign-reviewers, first-interaction-greet
          permission: none
          issue-type: pull-request
